#!/usr/bin/env bash
# This script displays information about subdomains

# Define a function to get the subdomain information
get_subdomain_info() {
	  local domain=$1
	    local subdomain=$2
	      local ip=$(dig +short ${subdomain}.${domain} | awk '{print $1}')
	        local record_type=$(dig +short ${subdomain}.${domain} | awk '{print $2}')
		  echo "The subdomain ${subdomain} is a ${record_type} record and points to ${ip}"
	  }

  # Check if the subdomain parameter is provided
  if [ -z "$2" ]; then
	    # If not, display information for the default subdomains
	      get_subdomain_info $1 "www"
	        get_subdomain_info $1 "lb-01"
		  get_subdomain_info $1 "web-01"
		    get_subdomain_info $1 "web-02"
	    else
		      # If provided, display information for the specified subdomain
		        get_subdomain_info $1 $2
  fi
